jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES

server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  jackson:
    default-property-inclusion: NON_EMPTY

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-group

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: ENC(ult8/xk6Dci21knOQ2UfSM1db47MaTX/)
  expiration:
    access: 3600000

message-broker:
  topic:
    cooking: cooking
    cooking-success: cooking-success
    cooking-fail: cooking-fail
    delivery: delivery
    delivery-success: delivery-success
    delivery-fail: delivery-fail
    rejection: rejection
